name = "notification-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[build]
command = "pnpm build"

[dev]
port = 8787

[[durable_objects.bindings]]
name = "WEBSOCKET"
class_name = "WebSocketDO" 